### ISSUE TITLE
intro-1: some ideas

### ISSUE THREAD

**Issue by 3v0k4** [AkkarinForest/Haskell-Workshop#1]
* Consider removing the sentence “Notice that the function preceding the $ must accept 1 and only 1 argument which must be of the same type of what the following function returns”. Types are introduced later and mentioning them sooner could be confusing.
* Consider using https://www.stackage.org/ or https://hackage.haskell.org/ for docs instead of zvon.org.
* I'd suggest we don't even mention `$` and we also remove the "piping functions" section. Haskell code can be written without it. Also, I would argue is not as useful as `|>`. Especially because `$` works the other way around.
* Connected to the above, this could be really confusing for newcomers `plusTwo x =  (+) 1 $ (+) 1 x`
* I think we could explain a bit better the part about `Int -> a -> [a]` in particular the following sentence:
    > and some mystical type `a`. What is that? In type signatures lower case letters indicate that a value can have more than one type. In this case it could be anything: number, string, bool... Whatever you provide the function will replicate it and returs a list of that objects. Because the letter `a` is in both places `a -> [a]` this means that the returned list will have the same types as the provided values. Try to guess the result of the following, which one will return an error? Check your answers in the GHCi:

**Comment by 3v0k4** [comment]
Happy to give rephrasing some things a try if you need 👍

**Comment by 3v0k4** [comment]
What do you think of using Ruby lambdas in "Functions passed as arguments"?

For example, instead of

```ruby
>> def shout(sen)
>>  sen.upcase
>> end

>> def greet(name, fnc)
>>   fnc.call("hello " + name)
>> end

>> greet("haskell", method(:shout))
=> "HELLO HASKELL"
```

We could use

```ruby
shout = ->(sen) { sen.upcase }

greet = ->(name, fnc) { fnc.call("hello " + name) }

greet("haskell", shout)
=> "HELLO HASKELL"
```

That's what I'm doing in intro-2. I think people are more exposed to lambdas than the trick with `method`.

**Comment by alex-suminski** [comment]
About "Functions passed as arguments" - I don't have any preference, we can use lambdas. But did you check the example you provided? Cause it doesn't seem to work:
```
>> shout = ->(sen) { sen.upcase }
=> #<Proc:0x007fd88ed81fd0@(irb):46 (lambda)>
>> greet = ->(name, fnc) { fnc.call("hello " + name) }
=> #<Proc:0x007fd88fc00ac0@(irb):47 (lambda)>
>> greet("haskell", shout)
ArgumentError: wrong number of arguments (given 2, expected 0)
	from (irb):6:in `greet'
	from (irb):48
```

**Comment by alex-suminski** [comment]
`Consider removing the sentence “Notice that the function preceding the $ must accept 1 and only 1 argument which must be of the same type of what the following function returns”. Types are introduced later and mentioning them sooner could be confusing.`
What do you think is confusing here? The tutorial is aimed at an audience that is familiar with basic programming concepts, so I think the idea of types will be known to everyone. And the details of how types work in Haskell are not needed to understand this part.

`Consider using https://www.stackage.org/ or https://hackage.haskell.org/ for docs instead of zvon.org.`
Yes, let's discuss that on the call. Like I mentioned earlier I want us to choose one documentation to reference and use it consistently.

`I think we could explain a bit better the part about Int -> a -> [a] in particular the following sentence:`
It's clear to me, probably because I wrote it 😄 so if you wanna give it a try and rephrase it, go-ahead.

**Comment by 3v0k4** [comment]
I'll wait for you to close this before reviewing all the workshop. After we both reviewed, I'll create the doodle for either one of the following:

- Wednesday 16:00–17:00
- Wednesday 17:00–18:00
- Thursday 16:00–17:00
- Thursday 17:00–18:00

Let's track the review in #5
